const express=require('express');
const rateLimit=require('express-rate-limit');
const store=require('../database/store');
const {auth,requireRole}=require('../middleware/auth');
const {cleanString,isEmail}=require('../utils/validation');
const router=express.Router();
const loginLimiter=rateLimit({windowMs:15*60*1000,max:20,standardHeaders:true,legacyHeaders:false,message:{ok:false,error:{code:'RATE_LIMITED',message:'Terlalu banyak percobaan. Coba lagi nanti.'}}});

const authController=require('../controllers/auth');
router.post('/auth/admin/login',loginLimiter,authController.adminLogin);
router.post('/auth/admin/verify-otp',loginLimiter,authController.verifyOtp);
router.post('/auth/personnel/login',loginLimiter,authController.personnelLogin);
router.post('/auth/personnel/verify-otp',loginLimiter,authController.verifyOtp);
router.get('/auth/session',authController.session);
router.post('/auth/session/refresh',authController.refresh);
router.post('/auth/logout',authController.logout);

router.get('/bootstrap',async(req,res)=>{res.json({ok:true,data:{name:'IKSN',status:'OPERATIONAL',node:'HAYDAR-S/01',access:'CONTROLLED',disclaimer:'FICTIONAL INSTITUTIONAL PROTOTYPE'}})});
router.get('/health',async(req,res)=>{res.json({ok:true,service:'IKSN',status:'operational'})});

router.post('/requests',async(req,res)=>{const d=req.body||{};if(!cleanString(d.full_name)||!isEmail(d.email)||!cleanString(d.organization)||!cleanString(d.reason))return res.status(422).json({ok:false,error:{code:'VALIDATION_ERROR',message:'Nama, email, organisasi, dan alasan wajib diisi.'}});if(d.photo_data){const raw=String(d.photo_data);if(!/^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/=]+$/.test(raw)||Buffer.byteLength(raw,'base64')>2*1024*1024)return res.status(422).json({ok:false,error:{code:'PHOTO_INVALID',message:'Foto tidak valid atau melebihi batas 2 MB.'}});} const r=await store.createAccessRequest({full_name:cleanString(d.full_name,120),email:cleanString(d.email,180),phone:cleanString(d.phone,40),date_of_birth:d.date_of_birth,country:cleanString(d.country,80),city:cleanString(d.city,80),organization:cleanString(d.organization,120),department:cleanString(d.department,120),position:cleanString(d.position,120),personnel_type:cleanString(d.personnel_type,80),employee_number:cleanString(d.employee_number,80),reason:cleanString(d.reason,500),clearance_requested:cleanString(d.clearance_requested,40),photo_name:cleanString(d.photo_name,255),face_verified:!!d.face_verified});await store.audit(null,'PUBLIC','ACCESS_REQUESTED',r.id,{email:r.email});res.status(201).json({ok:true,data:{requestId:r.id,status:r.status}});});
router.get('/requests/status',async(req,res)=>{const id=cleanString(req.query.id,80);if(!id)return res.status(422).json({ok:false,error:{code:'VALIDATION_ERROR',message:'Request ID required.'}});const r=await store.getAccessRequest(id);if(!r)return res.status(404).json({ok:false,error:{code:'NOT_FOUND',message:'Request tidak ditemukan.'}});res.json({ok:true,data:{requestId:r.id,status:r.status,submittedAt:r.submitted_at}});});

router.get('/admin/requests',auth,requireRole('ADMIN'),async(req,res)=>res.json({ok:true,data:await store.listAccessRequests()}));
router.post('/admin/requests/:id/approve',auth,requireRole('ADMIN'),async(req,res)=>{try{const r=await store.approveRequest(req.params.id,req.user.id);res.json({ok:true,data:r});}catch(e){res.status(e.status||500).json({ok:false,error:{code:e.status===404?'NOT_FOUND':'APPROVAL_FAILED',message:e.status===404?e.message:'Approval gagal.'}})}});
router.post('/admin/requests/:id/reject',auth,requireRole('ADMIN'),async(req,res)=>{try{const r=await store.rejectRequest(req.params.id,req.user.id);res.json({ok:true,data:r});}catch(e){res.status(e.status||500).json({ok:false,error:{code:e.status===404?'NOT_FOUND':'REJECTION_FAILED',message:e.status===404?e.message:'Rejection gagal.'}})}});

router.get('/personnel/me',auth,requireRole('PERSONNEL'),async(req,res)=>res.json({ok:true,data:await store.findPersonnelByUserId(req.user.id)}));
router.get('/admin/personnel',auth,requireRole('ADMIN'),async(req,res)=>res.json({ok:true,data:await store.listPersonnel({search:cleanString(req.query.search,80),status:cleanString(req.query.status,40)})}));
router.get('/admin/personnel/:id',auth,requireRole('ADMIN'),async(req,res)=>{const p=await store.findPersonnelById(req.params.id);if(!p)return res.status(404).json({ok:false,error:{code:'NOT_FOUND',message:'Personnel tidak ditemukan.'}});res.json({ok:true,data:p});});
router.post('/admin/personnel/:id/restore',auth,requireRole('ADMIN'),async(req,res)=>{const p=await store.findPersonnelById(req.params.id);if(!p)return res.status(404).json({ok:false,error:{code:'NOT_FOUND',message:'Personnel tidak ditemukan.'}});const updated=await store.updatePersonnelStatus(p.id,'APPROVED',req.user.id);res.json({ok:true,data:updated});});
for(const action of ['suspend','revoke','terminate'])router.post(`/admin/personnel/:id/${action}`,auth,requireRole('ADMIN'),async(req,res)=>{const p=await store.findPersonnelById(req.params.id);if(!p)return res.status(404).json({ok:false,error:{code:'NOT_FOUND',message:'Personnel tidak ditemukan.'}});const next=action==='suspend'?'SUSPENDED':action==='revoke'?'REVOKED':'TERMINATED';const updated=await store.updatePersonnelStatus(p.id,next,req.user.id);res.json({ok:true,data:updated});});
router.delete('/admin/personnel/:id',auth,requireRole('ADMIN'),async(req,res)=>{const p=await store.findPersonnelById(req.params.id);if(!p)return res.status(404).json({ok:false,error:{code:'NOT_FOUND',message:'Personnel tidak ditemukan.'}});const deleted=await store.softDeletePersonnel(p.id,req.user.id);res.json({ok:true,data:{deleted}});});

router.post('/location/toggle',auth,requireRole('PERSONNEL'),async(req,res)=>{const enabled=!!req.body?.enabled;const p=await store.findPersonnelByUserId(req.user.id);if(!p)return res.status(404).json({ok:false,error:{code:'NOT_FOUND',message:'Personnel tidak ditemukan.'}});const updated=await store.setLocationSharing(p.id,enabled);await store.audit(req.user.id,'PERSONNEL',enabled?'LOCATION_ENABLED':'LOCATION_DISABLED',p.id,{sharing_enabled:enabled},req);res.json({ok:true,data:updated});});
router.post('/location',auth,requireRole('PERSONNEL'),async(req,res)=>{const p=await store.findPersonnelByUserId(req.user.id);if(!p||!p.location_sharing)return res.status(403).json({ok:false,error:{code:'LOCATION_CONSENT_REQUIRED',message:'Aktifkan berbagi lokasi terlebih dahulu.'}});const lat=Number(req.body?.latitude),lon=Number(req.body?.longitude),accuracy=Number(req.body?.accuracy||0);if(!Number.isFinite(lat)||lat<-90||lat>90||!Number.isFinite(lon)||lon<-180||lon>180)return res.status(422).json({ok:false,error:{code:'VALIDATION_ERROR',message:'Koordinat tidak valid.'}});const row=await store.addLocation({personnel_id:p.id,latitude:lat,longitude:lon,accuracy,timestamp:req.body?.timestamp||new Date().toISOString(),sharing_enabled:true});await store.audit(req.user.id,'PERSONNEL','LOCATION_UPDATE',p.id,{latitude:lat,longitude:lon,accuracy},req);res.json({ok:true,data:row});});
router.get('/location/me',auth,requireRole('PERSONNEL'),async(req,res)=>{const p=await store.findPersonnelByUserId(req.user.id);res.json({ok:true,data:{sharing:!!p?.location_sharing,location:await store.getMyLocation(p.id)}})});
router.get('/admin/locations',auth,requireRole('ADMIN'),async(req,res)=>res.json({ok:true,data:await store.getAdminLocations()}));

router.get('/messages/contacts',auth,requireRole('PERSONNEL'),async(req,res)=>res.json({ok:true,data:(await store.listPersonnel({status:'APPROVED'})).filter(p=>p.user_id!==req.user.id).map(p=>({id:p.id,user_id:p.user_id,personnel_code:p.personnel_code,full_name:p.full_name,email:p.email,department:p.department,status:p.status}))}));
router.post('/messages/conversations',auth,requireRole('PERSONNEL'),async(req,res)=>{const receiverId=cleanString(req.body?.receiver_id,80);const receiver=await store.findUserById(receiverId);if(!receiver||receiver.role!=='PERSONNEL'||receiver.id===req.user.id)return res.status(403).json({ok:false,error:{code:'FORBIDDEN',message:'Kontak tidak valid.'}});const target=await store.findPersonnelByUserId(receiverId);if(!target||target.status!=='APPROVED')return res.status(403).json({ok:false,error:{code:'FORBIDDEN',message:'Penerima belum approved.'}});const id=await store.findOrCreateConversation(req.user.id,receiverId);res.status(201).json({ok:true,data:{id}})});
router.get('/messages/conversations',auth,requireRole('PERSONNEL'),async(req,res)=>res.json({ok:true,data:await store.listConversations(req.user.id)}));
router.get('/messages/conversations/:id',auth,requireRole('PERSONNEL'),async(req,res)=>{if(!await store.conversationMember(req.params.id,req.user.id))return res.status(403).json({ok:false,error:{code:'FORBIDDEN',message:'Conversation access denied.'}});res.json({ok:true,data:await store.getMessages(req.params.id)})});
router.post('/messages',auth,requireRole('PERSONNEL'),async(req,res)=>{const receiverId=cleanString(req.body?.receiver_id,80),body=cleanString(req.body?.body,2000);if(!receiverId||!body)return res.status(422).json({ok:false,error:{code:'VALIDATION_ERROR',message:'Penerima dan pesan wajib diisi.'}});const receiver=await store.findUserById(receiverId);if(!receiver||receiver.role!=='PERSONNEL')return res.status(403).json({ok:false,error:{code:'FORBIDDEN',message:'Pesan hanya untuk personnel yang disetujui.'}});const target=await store.findPersonnelByUserId(receiverId);if(!target||target.status!=='APPROVED')return res.status(403).json({ok:false,error:{code:'FORBIDDEN',message:'Penerima belum approved.'}});const cid=await store.findOrCreateConversation(req.user.id,receiverId);const m=await store.createMessage({conversation_id:cid,sender_id:req.user.id,receiver_id:receiverId,body});res.status(201).json({ok:true,data:m});});
router.post('/messages/:id/read',auth,requireRole('PERSONNEL'),async(req,res)=>{const m=await store.markMessageRead(req.params.id,req.user.id);if(!m)return res.status(404).json({ok:false,error:{code:'NOT_FOUND',message:'Message tidak ditemukan.'}});res.json({ok:true,data:m})});
router.delete('/messages/:id',auth,requireRole('PERSONNEL'),async(req,res)=>res.json({ok:true,data:{deleted:await store.deleteMessage(req.params.id,req.user.id)}}));
router.get('/messages/unread-count',auth,requireRole('PERSONNEL'),async(req,res)=>res.json({ok:true,data:{count:await store.unreadCount(req.user.id)}}));

router.get('/notifications',auth,async(req,res)=>res.json({ok:true,data:await store.notificationsFor(req.user.id)}));
router.post('/notifications/:id/read',auth,async(req,res)=>{const n=await store.markNotificationRead(req.params.id,req.user.id);if(!n)return res.status(404).json({ok:false,error:{code:'NOT_FOUND',message:'Notification tidak ditemukan.'}});res.json({ok:true,data:n})});
router.get('/admin/audit',auth,requireRole('ADMIN'),async(req,res)=>res.json({ok:true,data:await store.auditList()}));

module.exports=router;
